<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_satuan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_satuan');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('m_satuan/m_satuan_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Model_satuan->json();
    }

    public function read($id) 
    {
        $row = $this->Model_satuan->get_by_id($id);
        if ($row) {
            $data = array(
		'id_satuan' => $row->id_satuan,
		'nama_satuan' => $row->nama_satuan,
		'keterangan' => $row->keterangan,
	    );
            $this->load->view('m_satuan/m_satuan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('m_satuan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('m_satuan/create_action'),
	    'id_satuan' => set_value('id_satuan'),
	    'nama_satuan' => set_value('nama_satuan'),
	    'keterangan' => set_value('keterangan'),
	);
        $this->load->view('m_satuan/m_satuan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_satuan' => $this->input->post('nama_satuan',TRUE),
		'keterangan' => $this->input->post('keterangan',TRUE),
	    );

            $this->Model_satuan->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('m_satuan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Model_satuan->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('m_satuan/update_action'),
		'id_satuan' => set_value('id_satuan', $row->id_satuan),
		'nama_satuan' => set_value('nama_satuan', $row->nama_satuan),
		'keterangan' => set_value('keterangan', $row->keterangan),
	    );
            $this->load->view('m_satuan/m_satuan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('m_satuan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_satuan', TRUE));
        } else {
            $data = array(
		'nama_satuan' => $this->input->post('nama_satuan',TRUE),
		'keterangan' => $this->input->post('keterangan',TRUE),
	    );

            $this->Model_satuan->update($this->input->post('id_satuan', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('m_satuan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Model_satuan->get_by_id($id);

        if ($row) {
            $this->Model_satuan->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('m_satuan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('m_satuan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_satuan', 'nama satuan', 'trim|required');
	$this->form_validation->set_rules('keterangan', 'keterangan', 'trim|required');

	$this->form_validation->set_rules('id_satuan', 'id_satuan', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file M_satuan.php */
/* Location: ./application/controllers/M_satuan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-03-28 04:48:31 */
/* http://harviacode.com */