<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_satuan extends CI_Model
{

    public $table = 'akuntansi_m_satuan';
    public $id = 'id_satuan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_satuan,nama_satuan,keterangan');
        $this->datatables->from('akuntansi_m_satuan');
        //add this line for join
        //$this->datatables->join('table2', 'm_satuan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('m_satuan/read/$1'),'Read')." | ".anchor(site_url('m_satuan/update/$1'),'Update')." | ".anchor(site_url('m_satuan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_satuan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_satuan', $q);
	$this->db->or_like('nama_satuan', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_satuan', $q);
	$this->db->or_like('nama_satuan', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Model_satuan.php */
/* Location: ./application/models/Model_satuan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-03-28 04:48:31 */
/* http://harviacode.com */