<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_kelompok_coa extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->helper('nuris_helper');
        $this->load->model('Model_kelompok_coa');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    $user = wp_get_current_user();
    if ( !in_array( 'administrator', (array) $user->roles ) ) {
                
                redirect(base_url('denied'));
            }
        
    }

    public function index()
    {
       $this->template->load('template_admin','m_kelompok_coa/m_kelompok_coa_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Model_kelompok_coa->json();
    }

    public function read($id) 
    {
        $row = $this->Model_kelompok_coa->get_by_id($id);
        if ($row) {
            $data = array(
		'uniqid' => $row->uniqid,
		'id_kelompok_coa' => $row->id_kelompok_coa,
		'nama_kelompok_coa' => $row->nama_kelompok_coa,
	    );
           $this->template->load('template_admin','m_kelompok_coa/m_kelompok_coa_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url('m_kelompok_coa'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Tambah',
            'action' => base_url('m_kelompok_coa/create_action'),
	    'uniqid' => set_value('uniqid'),
	    'id_kelompok_coa' => set_value('id_kelompok_coa'),
	    'nama_kelompok_coa' => set_value('nama_kelompok_coa'),
	);
       $this->template->load('template_admin','m_kelompok_coa/m_kelompok_coa_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_kelompok_coa' => $this->input->post('id_kelompok_coa',TRUE),
		'nama_kelompok_coa' => $this->input->post('nama_kelompok_coa',TRUE),
	    );

            $this->Model_kelompok_coa->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(base_url('m_kelompok_coa'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Model_kelompok_coa->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Ubah',
                'action' => base_url('m_kelompok_coa/update_action'),
		'uniqid' => set_value('uniqid', $row->uniqid),
		'id_kelompok_coa' => set_value('id_kelompok_coa', $row->id_kelompok_coa),
		'nama_kelompok_coa' => set_value('nama_kelompok_coa', $row->nama_kelompok_coa),
	    );
           $this->template->load('template_admin','m_kelompok_coa/m_kelompok_coa_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url('m_kelompok_coa'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('uniqid', TRUE));
        } else {
            $data = array(
		'id_kelompok_coa' => $this->input->post('id_kelompok_coa',TRUE),
		'nama_kelompok_coa' => $this->input->post('nama_kelompok_coa',TRUE),
	    );

            $this->Model_kelompok_coa->update($this->input->post('uniqid', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(base_url('m_kelompok_coa'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Model_kelompok_coa->get_by_id($id);

        if ($row) {
            $this->Model_kelompok_coa->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(base_url('m_kelompok_coa'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url('m_kelompok_coa'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_kelompok_coa', 'id kelompok coa', 'trim|required');
	$this->form_validation->set_rules('nama_kelompok_coa', 'nama kelompok coa', 'trim|required');

	$this->form_validation->set_rules('uniqid', 'uniqid', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file M_kelompok_coa.php */
/* Location: ./application/controllers/M_kelompok_coa.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-03-10 04:31:31 */
/* http://harviacode.com */